[package]
name = "kill-orphan"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.20"
env_logger = "0.10.1"
signal-hook = "0.3.17"
sysinfo = "0.30.5"
cfg-if = "1.0"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"
duct = "0.13.7"
tempfile = "3.9.0"